Medium: safely create tempoary files After my previous post, I realised that there are lots of other places in the code where mktemp is used and more importantly, alternate unsafe code is used. So I have had a crack at cleaning things up.
------------------------------------------------------------------------

There are currently at least two problems with maketempfile.
Firstly, there is a race in the following constrct:

   rm -f "$F"; touch "$F"

As an attacker could potitinally create a symlink to "$F" between
the call to rm and the call to touch.

Secondly the use of $RANDOM appears to be a bashism.
On dash its usage in BasicSanityCheck appears to evaluate to
the empty string. See Debian Bug #489607, http://bugs.debian.org/489607

This patch takes the approach of using mkdir, which is atomic,
to create a safe place to store the logfile the tempoary directory
that is used by the filesystem check.

The patch also makes sure that the return value is checked
and the script exits cleanly if an error occurs.

This code is always used, there seems no point is providing
a robust fallback to mktemp - if its robust, it can be used :-)

For a discussion of creating tempoary files in shell see
http://www.linuxsecurity.com/content/view/115462/81/

Signed-off-by: Simon Horman <horms@verge.net.au>

diff --git a/heartbeat/lib/BasicSanityCheck.in b/heartbeat/lib/BasicSanityCheck.in
--- a/heartbeat/lib/BasicSanityCheck.in
+++ b/heartbeat/lib/BasicSanityCheck.in
@@ -49,7 +49,6 @@ CRMTEST="@PYTHON@ $SCRIPTDIR/cts/CTSlab.py --bsc"
 SNMPAGENTTEST=$SCRIPTDIR/SNMPAgentSanityCheck
 BASE64_MD5_TEST=$HBLIB/base64_md5_test
 MALLOC_CHECK_=2; export MALLOC_CHECK_
-MKTEMP=@MKTEMP@
 TESTPROG=@TEST@
 #
 IDENTSTRING="Linux-HA TEST configuration file - REMOVEME!!"
@@ -64,35 +63,28 @@ SIGLIST="0 1 2 3 6 15"
 
 errcount=0
 
-# Make temp files the paranoid way...
-maketempfile() {
-#
-#	Use mktemp if we have it, otherwise...
-#
-#	Construct a difficult-to-guess filename if we don't
-#	Make sure non-mktemp files can't be subverted
-#	$RANDOM is not strictly necessary, but nice to have...
-#
-  if
-    test "x$MKTEMP" != "x" \
-      && F=`$MKTEMP /tmp/lha-XXXXXX` && [ ! -z "$F" -a -f "$F" ]
-  then
-    echo $F
-  else
-    while
-      echo >/dev/null &
-      F=/tmp/lha-${RANDOM}-$$-$!
-      rm -f "$F"; touch "$F"
-      # Try again if we don't own it, or it's a symlink
-      # Or somehow not a regular file...
-      $TESTPROG ! -O "$F" -o -L "$F" -o ! -f "$F"
-    do
-     : Try again...
-    done
-    echo $F
-  fi
+# Make a safe place to store logs
+maketempdir()
+{
+	local i=1
+	local tmp
+
+	while [ $i -gt 0 ]; do
+		tmp="/tmp/lha-dir-$$-$i"
+		if (umask 077 && mkdir "$tmp"); then
+			echo "$tmp"
+			return 0
+		fi
+		i=$((i+1))
+	done
+
+	echo "Could not create tempoary directory to store logs" >& 2
+	return 1
 }
-LOGFILE=`maketempfile`
+
+LOGDIR=`maketempdir` || exit 1
+LOGFILE="$LOGDIR/log"
+touch "$LOGFILE"
 
 cd $HADIR
 ulimit -c unlimited
@@ -328,6 +320,7 @@ SaveLog() {
   SAVELOG=/tmp/linux-ha.testlog
   chmod a+r $LOGFILE
   mv $LOGFILE $SAVELOG
+  rm -rf "$LOGDIR"
   echo "$errcount errors. Log file is stored in $SAVELOG"
 }
 
@@ -985,7 +978,8 @@ TestRA() {
 	fi
 
 	if [ `uname -s` = 'Linux' ]; then
-		MNT_DIR=`@MKTEMP@ -d /tmp/lha-dir-XXXXXXXXXXX`
+		MNT_DIR="$LOGDIR/mnt"
+		mkdir "$MNT_DIR"
 		echo "Testing RA: Filesystem" | tee -a $LOGFILE
 		$OCF_TESTER -o device=/dev/null -o fstype=proc -o directory=$MNT_DIR \
 			-n DemoFS $RADIR/Filesystem >>$LOGFILE 2>&1
